package org.csps.backend.domain.enums;

public enum AdminPosition {
    PRESIDENT,
    VP_INTERNAL,
    VP_EXTERNAL,
    SECRETARY,
    TREASURER,
    ASSISTANT_TREASURER,
    AUDITOR,
    PIO,
    PRO,
    CHIEF_VOLUNTEER,
    FIRST_YEAR_REPRESENTATIVE,
    SECOND_YEAR_REPRESENTATIVE,
    THIRD_YEAR_REPRESENTATIVE,
    FOURTH_YEAR_REPRESENTATIVE,
    DEVELOPER
}
